#!/usr/bin/env bash

set -e

# TODO: ideally we could pass this into the flake?
sed -i 's/"x86_64-linux" "i686-linux" "x86_64-darwin" "aarch64-linux"/"x86_64-linux" "x86_64-darwin"/' flake.nix

script=$(nix-build -A outputs.hydraJobs.installerScript --no-out-link)
installerHash=$(cut -b12-43 $script)

cat << EOF > installer.sh
sh <(curl -sfL https://$CACHIX_NAME.cachix.org/serve/$installerHash/install) --tarball-url https://$CACHIX_NAME.cachix.org/serve "\$@"
EOF
chmod +x installer.sh